import type { MetaResponse } from "./types";

function safeString(value: unknown, fallback = ""): string {
  const trimmed = String(value || "").trim();
  return trimmed || fallback;
}

function shellQuote(value: string): string {
  return "'" + String(value).replace(/'/g, "'\"'\"'") + "'";
}

function pathParent(path: string): string {
  const trimmed = String(path || "").trim().replace(/\/+$/g, "");
  if (!trimmed) {
    return ".";
  }
  const index = trimmed.lastIndexOf("/");
  if (index < 0) {
    return ".";
  }
  if (index === 0) {
    return "/";
  }
  return trimmed.slice(0, index);
}

function pathBase(path: string): string {
  const trimmed = String(path || "").trim().replace(/\/+$/g, "");
  if (!trimmed) {
    return ".";
  }
  const index = trimmed.lastIndexOf("/");
  return index < 0 ? trimmed : trimmed.slice(index + 1);
}

function comment(value: string): string {
  return "# " + String(value || "").replace(/\s+/g, " ").trim();
}

export function buildBackupScript(meta: MetaResponse): string {
  const appName = safeString(meta.name, "noterious");
  const generatedAt = safeString(meta.serverTime, new Date().toISOString());
  const runtimeVaultPath = safeString(meta.runtimeVault && meta.runtimeVault.vaultPath, "/path/to/noterious-vault");
  const dataDir = safeString(meta.dataDir, "/path/to/noterious-data");
  const database = safeString(meta.database, dataDir ? (dataDir.replace(/\/+$/g, "") + "/index.sqlite") : "/path/to/noterious-data/index.sqlite");
  const currentScopeVault = safeString(meta.currentVault && meta.currentVault.vaultPath);

  const lines = [
    "#!/usr/bin/env sh",
    "set -eu",
    "",
    comment("Generated by Noterious on " + generatedAt + "."),
    comment("Usage: sh ./noterious-backup.sh [/path/to/backup-root]"),
    comment("This backs up the full deployment: runtime vault root + data dir."),
    comment("The SQLite index is rebuildable, but the rest of the data dir is not."),
    currentScopeVault && currentScopeVault !== runtimeVaultPath
      ? comment("Current UI scope at generation time: " + currentScopeVault)
      : "",
    "",
    "APP_NAME=" + shellQuote(appName),
    "VAULT_PATH=" + shellQuote(runtimeVaultPath),
    "DATA_DIR=" + shellQuote(dataDir),
    "DATABASE_PATH=" + shellQuote(database),
    "",
    "BACKUP_ROOT=./noterious-backups",
    "if [ \"$#\" -ge 1 ]; then",
    "  BACKUP_ROOT=\"$1\"",
    "fi",
    "",
    "STAMP=\"$(date -u +%Y%m%dT%H%M%SZ)\"",
    "TARGET_DIR=\"$BACKUP_ROOT/$APP_NAME-$STAMP\"",
    "",
    "mkdir -p \"$TARGET_DIR\"",
    "",
    "tar -C " + shellQuote(pathParent(runtimeVaultPath)) + " -czf \"$TARGET_DIR/vault.tar.gz\" " + shellQuote(pathBase(runtimeVaultPath)),
    "tar -C " + shellQuote(pathParent(dataDir)) + " -czf \"$TARGET_DIR/data-dir.tar.gz\" " + shellQuote(pathBase(dataDir)),
    "",
    "cat <<EOF > \"$TARGET_DIR/RESTORE.txt\"",
    "Restore steps:",
    "1. Stop the Noterious server.",
    "2. Restore vault.tar.gz so this path exists again: " + runtimeVaultPath,
    "3. Restore data-dir.tar.gz so this path exists again: " + dataDir,
    "4. Start the server again.",
    "",
    "Notes:",
    "- SQLite index path: " + database,
    "- The SQLite index is rebuildable if needed.",
    "- History, trash, custom themes, auth state, and other server-managed files live under the data dir.",
    "EOF",
    "",
    "printf '%s\\n' \"Backup written to $TARGET_DIR\"",
    "printf '%s\\n' \"Created: vault.tar.gz, data-dir.tar.gz, RESTORE.txt\"",
  ];

  return lines.filter(Boolean).join("\n") + "\n";
}

export function backupScriptFilename(meta: MetaResponse): string {
  const isoTimestamp = safeString(meta.serverTime, new Date().toISOString()).replace(/[:]/g, "-");
  return "noterious-backup-" + isoTimestamp + ".sh";
}
